// Homepage components exports
export { HeroSection } from './HeroSection'
export { LiveClassesSection } from './LiveClassesSection'
export { SelfPacedCoursesSection } from './SelfPacedCoursesSection'
export { AllExamsSection } from './AllExamsSection'
export { AttendanceSection } from './AttendanceSection'
export { PendingActionsSection } from './PendingActionsSection'
export { MasteryPathSection } from './MasteryPathSection'
export { CTASection } from './CTASection'
export { HowItWorksSection } from './HowItWorksSection'
export { FeaturesSection } from './FeaturesSection'
export { RecentlyPlacedStudentsSection } from './RecentlyPlacedStudentsSection'
export { FooterComponent } from './FooterComponent'
